# .streamlit/secrets.toml

[connections.mysql_db]
dialect = "mysql"
driver = "mysqlconnector"
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
port = 4000
database = "test"
username = "32P8RUrU9kDoPtD.root"
password = "NKJd2e5VcCkbgTxQ"

[connections.mysql_db.kwargs]
ssl_verify_identity = true
ssl_ca = "/etc/ssl/certs/ca-certificates.crt"